# Release Pipeline (CD)
name: Push

on:
  push:
    branches:
      - master

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Add Semantic Release (Prerelease)
      uses: cycjimmy/semantic-release-action@v2
      with:
        semantic_version: 16
        branches: |    
          [
            {
              name: 'master', 
              prerelease: true
            }, 
          ]
        extra_plugins: |
          @semantic-release/git
          @semantic-release/changelog
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
