name: Release

on:
  push:
    branches:
      - master

jobs:
  releae:
    name: release
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Semantic Release
      uses: cycjimmy/semantic-release-action@v2
      with:
        branch: master
        extra_plugins: |
          @semantic-release/git
          @semantic-release/changelog
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
